language: node_js

node_js:
  - "0.11"
  - "0.10"

notifications:
  webhook:
    secure: "aYeLKUqavQ5Ka9R8WcDde7zCAiVE5u08ogn8OcUr73ubEp6oxGM+aJkC2GhCb3VIl2xgznkQulR+HeaRPt0V85HZuNGXAbe0NQxbzi84wXix7tShMxQr+7KQl6G01RKE2FGWRxw4aNHGD174K0TAmRUOh18MomnodS9U+kx/fHk="

services:
  - mongodb
  - redis
