language: node_js

node_js:
  - "0.11"
  - "0.10"

notifications:
  webhook:
    secure: "lfMDy/Nt+6kXcE15JrrMcLTwVN/oPED9BFad1DvhcHneUUVOPLk/9TlEiNw+QVl1j3V/W5Yta3bdD1qqx4JZkusBNp5IjcEHzH2qhbZQpK3yYK0lOElxjlNEmvJS0otWBw6xu2czwdh1MObOivH7FvlLHEwlzCtgq5f+4GNyQ+M="

services:
  - mongodb
  - redis
