language: node_js

node_js:
  - "0.11"
  - "0.10"

notifications:
  webhooks:
    secure: "Pq1XmiBlENs8jhUFbW+zbf5OXFeif8g8DedDaJ0B2zLmdGq7H43XXBlzO0zBrtZ382BoEXnqr9dZc2sWKyeipgUOnUdi8O0NbMRTO13auZqvwAuIMTpbNlOeaeWB/SCTqtJIF7AE326BZSLHBqAmOD6oAE0apSyfxKqOR+eNXF4="

services:
  - mongodb
  - redis
