language: node_js

node_js:
  - "0.11"
  - "0.10"

notifications:
  webhooks:
    secure: "Bs45uJIOk8MoguOUYOx4eh0bzv+qWqDnzFuCtap86YssHTb7bYisj8tBU9tqvyHXcUCLPSbTioquRw5rqSO7dyOnE2f9E5IvHGdVfObpcxKSsERm17rSDo5DjqTnDiyfjUPbmt/1NdyQH2djdMzVrnXe3TLBa6w7d6M7kpBXI7Y="

services:
  - mongodb
  - redis
