language: node_js

node_js:
  - "0.11"
  - "0.10"

notifications:
  webhook:
    secure: "bDbd7P9yXxs3R1QivpOuqtcSZMZrT3Ol6JH5an6uWC5i9LHULDORv4qhE4mEMpvp79xFqY5Xy1cQqYm7QCCrrqD5bgQqjWgzkPdzQJvsVYD5D3qZsKCq5+d5k0yeLpNkZxrNo9990z5YRgip0NgweehK+5GCd7dR0uPLPneMCk8="

services:
  - mongodb
  - redis
